//! Curated subset of common emoji + symbols, shipped as static data (not a
//! crate). Each entry is `(glyph, name, space-separated keywords)`. This is a
//! deliberately compact, high-frequency selection; extend the table to taste.

pub static EMOJI: &[(&str, &str, &str)] = &[
    // Smileys & emotion
    ("😀", "grinning face", "smile happy grin"),
    ("😃", "grinning face with big eyes", "smile happy joy"),
    ("😄", "grinning face with smiling eyes", "smile happy laugh"),
    ("😁", "beaming face with smiling eyes", "grin happy"),
    ("😆", "grinning squinting face", "laugh haha"),
    ("😅", "grinning face with sweat", "laugh sweat relief"),
    ("🤣", "rolling on the floor laughing", "rofl lol laugh"),
    ("😂", "face with tears of joy", "lol laugh cry funny"),
    ("🙂", "slightly smiling face", "smile"),
    ("🙃", "upside-down face", "silly sarcasm"),
    ("😉", "winking face", "wink flirt"),
    ("😊", "smiling face with smiling eyes", "blush happy"),
    ("😇", "smiling face with halo", "angel innocent"),
    ("🥰", "smiling face with hearts", "love adore"),
    ("😍", "smiling face with heart-eyes", "love crush"),
    ("🤩", "star-struck", "wow amazed star"),
    ("😘", "face blowing a kiss", "kiss love"),
    ("😗", "kissing face", "kiss"),
    ("😋", "face savoring food", "yum tasty delicious"),
    ("😛", "face with tongue", "tongue silly"),
    ("😜", "winking face with tongue", "tongue wink silly"),
    ("🤪", "zany face", "crazy goofy"),
    ("🤨", "face with raised eyebrow", "skeptical suspicious"),
    ("🧐", "face with monocle", "thinking inspect"),
    ("🤓", "nerd face", "geek glasses smart"),
    ("😎", "smiling face with sunglasses", "cool sunglasses"),
    ("🥳", "partying face", "party celebrate birthday"),
    ("😏", "smirking face", "smirk smug"),
    ("😒", "unamused face", "meh annoyed"),
    ("😞", "disappointed face", "sad"),
    ("😔", "pensive face", "sad sorrow"),
    ("😟", "worried face", "worry concern"),
    ("😕", "confused face", "confused unsure"),
    ("🙁", "slightly frowning face", "sad frown"),
    ("😣", "persevering face", "struggle"),
    ("😖", "confounded face", "frustrated"),
    ("😫", "tired face", "tired exhausted"),
    ("😩", "weary face", "weary tired"),
    ("🥺", "pleading face", "puppy beg please"),
    ("😢", "crying face", "cry sad tear"),
    ("😭", "loudly crying face", "sob cry bawl"),
    ("😤", "face with steam from nose", "angry frustrated"),
    ("😠", "angry face", "angry mad"),
    ("😡", "enraged face", "angry rage furious"),
    ("🤬", "face with symbols on mouth", "swearing curse"),
    ("🤯", "exploding head", "mind blown shocked"),
    ("😳", "flushed face", "embarrassed surprised"),
    ("🥵", "hot face", "hot heat sweat"),
    ("🥶", "cold face", "cold freezing"),
    ("😱", "face screaming in fear", "scream scared shock"),
    ("😨", "fearful face", "scared fear"),
    ("😰", "anxious face with sweat", "anxious nervous"),
    ("😥", "sad but relieved face", "phew relief"),
    ("🤗", "smiling face with open hands", "hug"),
    ("🤔", "thinking face", "think hmm"),
    ("🤭", "face with hand over mouth", "oops giggle"),
    ("🤫", "shushing face", "quiet shh secret"),
    ("🤥", "lying face", "lie pinocchio"),
    ("😶", "face without mouth", "speechless blank"),
    ("😐", "neutral face", "meh blank"),
    ("😑", "expressionless face", "blank"),
    ("😬", "grimacing face", "awkward grimace"),
    ("🙄", "face with rolling eyes", "eyeroll annoyed"),
    ("😯", "hushed face", "surprised"),
    ("😴", "sleeping face", "sleep zzz tired"),
    ("🤤", "drooling face", "drool"),
    ("😪", "sleepy face", "sleepy tired"),
    ("😵", "dizzy face", "dizzy ko"),
    ("🤐", "zipper-mouth face", "quiet secret"),
    ("🥴", "woozy face", "drunk woozy"),
    ("🤢", "nauseated face", "sick gross"),
    ("🤮", "face vomiting", "vomit sick puke"),
    ("🤧", "sneezing face", "sneeze sick"),
    ("😷", "face with medical mask", "mask sick"),
    ("🤒", "face with thermometer", "sick fever"),
    ("🤕", "face with head-bandage", "hurt injured"),
    ("🤑", "money-mouth face", "money rich"),
    ("🤠", "cowboy hat face", "cowboy"),
    ("😈", "smiling face with horns", "devil evil"),
    ("👿", "angry face with horns", "devil imp"),
    ("💀", "skull", "dead death skull"),
    ("👻", "ghost", "ghost halloween boo"),
    ("👽", "alien", "alien ufo"),
    ("🤖", "robot", "robot bot"),
    ("💩", "pile of poo", "poop crap"),
    ("🤡", "clown face", "clown"),
    // Gestures & body
    ("👍", "thumbs up", "yes like approve good"),
    ("👎", "thumbs down", "no dislike bad"),
    ("👌", "OK hand", "ok perfect"),
    ("✌️", "victory hand", "peace victory"),
    ("🤞", "crossed fingers", "luck hope"),
    ("🤟", "love-you gesture", "love rock"),
    ("🤘", "sign of the horns", "rock metal"),
    ("🤙", "call me hand", "call shaka"),
    ("👈", "backhand index pointing left", "left point"),
    ("👉", "backhand index pointing right", "right point"),
    ("👆", "backhand index pointing up", "up point"),
    ("👇", "backhand index pointing down", "down point"),
    ("☝️", "index pointing up", "up one"),
    ("✋", "raised hand", "stop high five"),
    ("🤚", "raised back of hand", "stop"),
    ("🖐️", "hand with fingers splayed", "hand"),
    ("🖖", "vulcan salute", "spock star trek"),
    ("👋", "waving hand", "wave hello bye"),
    ("🤝", "handshake", "deal agreement"),
    ("👏", "clapping hands", "clap applause"),
    ("🙌", "raising hands", "praise celebrate"),
    ("🙏", "folded hands", "pray thanks please"),
    ("✊", "raised fist", "fist power"),
    ("👊", "oncoming fist", "punch bump"),
    ("🤛", "left-facing fist", "fist bump"),
    ("🤜", "right-facing fist", "fist bump"),
    ("💪", "flexed biceps", "muscle strong gym"),
    ("👀", "eyes", "eyes look see"),
    ("👁️", "eye", "eye"),
    ("🧠", "brain", "brain smart"),
    ("👅", "tongue", "tongue"),
    ("👄", "mouth", "lips mouth"),
    ("❤️", "red heart", "love heart"),
    ("🧡", "orange heart", "love heart orange"),
    ("💛", "yellow heart", "love heart yellow"),
    ("💚", "green heart", "love heart green"),
    ("💙", "blue heart", "love heart blue"),
    ("💜", "purple heart", "love heart purple"),
    ("🖤", "black heart", "love heart black"),
    ("🤍", "white heart", "love heart white"),
    ("🤎", "brown heart", "love heart brown"),
    ("💔", "broken heart", "heartbreak sad"),
    ("💕", "two hearts", "love hearts"),
    ("💖", "sparkling heart", "love sparkle"),
    ("💘", "heart with arrow", "cupid love"),
    ("💝", "heart with ribbon", "gift love"),
    ("💯", "hundred points", "100 perfect score"),
    ("💢", "anger symbol", "angry mad"),
    ("💥", "collision", "boom explosion"),
    ("💫", "dizzy", "stars dizzy"),
    ("💦", "sweat droplets", "water sweat splash"),
    ("💤", "zzz", "sleep zzz"),
    // People & roles
    ("👶", "baby", "baby infant"),
    ("🧒", "child", "child kid"),
    ("👦", "boy", "boy"),
    ("👧", "girl", "girl"),
    ("🧑", "person", "person adult"),
    ("👨", "man", "man"),
    ("👩", "woman", "woman"),
    ("🧔", "person beard", "beard"),
    ("👴", "old man", "grandpa old"),
    ("👵", "old woman", "grandma old"),
    ("👮", "police officer", "cop police"),
    ("🕵️", "detective", "spy detective"),
    ("👷", "construction worker", "builder worker"),
    ("👸", "princess", "princess"),
    ("🤴", "prince", "prince"),
    ("👰", "person with veil", "bride wedding"),
    ("🤵", "person in tuxedo", "groom suit"),
    ("🎅", "Santa Claus", "santa christmas"),
    ("🦸", "superhero", "hero"),
    ("🦹", "supervillain", "villain"),
    ("🧙", "mage", "wizard magic"),
    ("🧚", "fairy", "fairy"),
    ("👼", "baby angel", "angel cherub"),
    ("🤰", "pregnant woman", "pregnant"),
    ("🚶", "person walking", "walk"),
    ("🏃", "person running", "run"),
    ("💃", "woman dancing", "dance"),
    ("🕺", "man dancing", "dance"),
    // Animals & nature
    ("🐶", "dog face", "dog puppy"),
    ("🐱", "cat face", "cat kitten"),
    ("🐭", "mouse face", "mouse"),
    ("🐹", "hamster", "hamster"),
    ("🐰", "rabbit face", "bunny rabbit"),
    ("🦊", "fox", "fox"),
    ("🐻", "bear", "bear"),
    ("🐼", "panda", "panda"),
    ("🐨", "koala", "koala"),
    ("🐯", "tiger face", "tiger"),
    ("🦁", "lion", "lion"),
    ("🐮", "cow face", "cow"),
    ("🐷", "pig face", "pig"),
    ("🐸", "frog", "frog"),
    ("🐵", "monkey face", "monkey"),
    ("🐔", "chicken", "chicken"),
    ("🐧", "penguin", "penguin"),
    ("🐦", "bird", "bird"),
    ("🦆", "duck", "duck"),
    ("🦅", "eagle", "eagle"),
    ("🦉", "owl", "owl"),
    ("🦄", "unicorn", "unicorn"),
    ("🐝", "honeybee", "bee"),
    ("🐛", "bug", "bug caterpillar"),
    ("🦋", "butterfly", "butterfly"),
    ("🐌", "snail", "snail"),
    ("🐢", "turtle", "turtle"),
    ("🐍", "snake", "snake"),
    ("🐙", "octopus", "octopus"),
    ("🦑", "squid", "squid"),
    ("🦀", "crab", "crab"),
    ("🐠", "tropical fish", "fish"),
    ("🐟", "fish", "fish"),
    ("🐬", "dolphin", "dolphin"),
    ("🐳", "spouting whale", "whale"),
    ("🦈", "shark", "shark"),
    ("🐊", "crocodile", "crocodile alligator"),
    ("🐘", "elephant", "elephant"),
    ("🦏", "rhinoceros", "rhino"),
    ("🐴", "horse face", "horse"),
    ("🦓", "zebra", "zebra"),
    ("🐑", "ewe", "sheep"),
    ("🐐", "goat", "goat"),
    ("🐓", "rooster", "rooster"),
    ("🦃", "turkey", "turkey thanksgiving"),
    ("🐲", "dragon face", "dragon"),
    ("🌵", "cactus", "cactus"),
    ("🌲", "evergreen tree", "tree pine"),
    ("🌳", "deciduous tree", "tree"),
    ("🌴", "palm tree", "palm tropical"),
    ("🌱", "seedling", "plant sprout"),
    ("🌿", "herb", "plant leaf"),
    ("🍀", "four leaf clover", "luck clover"),
    ("🍁", "maple leaf", "leaf autumn"),
    ("🌷", "tulip", "flower tulip"),
    ("🌹", "rose", "flower rose"),
    ("🌺", "hibiscus", "flower"),
    ("🌻", "sunflower", "flower sun"),
    ("🌸", "cherry blossom", "flower sakura"),
    ("💐", "bouquet", "flowers"),
    ("🌍", "globe showing Europe-Africa", "earth world globe"),
    ("🌎", "globe showing Americas", "earth world globe"),
    ("🌏", "globe showing Asia-Australia", "earth world globe"),
    ("⭐", "star", "star"),
    ("🌟", "glowing star", "star sparkle"),
    ("✨", "sparkles", "sparkle shiny"),
    ("⚡", "high voltage", "lightning bolt power"),
    ("🔥", "fire", "fire hot lit flame"),
    ("🌈", "rainbow", "rainbow"),
    ("☀️", "sun", "sun sunny"),
    ("⛅", "sun behind cloud", "cloud weather"),
    ("☁️", "cloud", "cloud"),
    ("🌙", "crescent moon", "moon night"),
    ("❄️", "snowflake", "snow cold winter"),
    ("⛄", "snowman without snow", "snowman winter"),
    ("💧", "droplet", "water drop"),
    ("🌊", "water wave", "wave ocean sea"),
    // Food & drink
    ("🍎", "red apple", "apple fruit"),
    ("🍌", "banana", "banana fruit"),
    ("🍇", "grapes", "grapes fruit"),
    ("🍓", "strawberry", "strawberry fruit"),
    ("🍊", "tangerine", "orange fruit"),
    ("🍉", "watermelon", "watermelon fruit"),
    ("🍑", "peach", "peach fruit butt"),
    ("🍒", "cherries", "cherry fruit"),
    ("🥑", "avocado", "avocado"),
    ("🍅", "tomato", "tomato"),
    ("🌽", "ear of corn", "corn"),
    ("🥕", "carrot", "carrot"),
    ("🥔", "potato", "potato"),
    ("🍞", "bread", "bread"),
    ("🧀", "cheese wedge", "cheese"),
    ("🥚", "egg", "egg"),
    ("🍳", "cooking", "egg fried breakfast"),
    ("🥓", "bacon", "bacon"),
    ("🍔", "hamburger", "burger"),
    ("🍟", "french fries", "fries"),
    ("🍕", "pizza", "pizza"),
    ("🌭", "hot dog", "hotdog"),
    ("🌮", "taco", "taco"),
    ("🌯", "burrito", "burrito"),
    ("🍜", "steaming bowl", "ramen noodles"),
    ("🍣", "sushi", "sushi"),
    ("🍱", "bento box", "bento"),
    ("🍙", "rice ball", "rice onigiri"),
    ("🍦", "soft ice cream", "icecream"),
    ("🍩", "doughnut", "donut"),
    ("🍪", "cookie", "cookie"),
    ("🎂", "birthday cake", "cake birthday"),
    ("🍰", "shortcake", "cake"),
    ("🍫", "chocolate bar", "chocolate"),
    ("🍬", "candy", "candy sweet"),
    ("🍿", "popcorn", "popcorn movie"),
    ("☕", "hot beverage", "coffee tea"),
    ("🍵", "teacup without handle", "tea"),
    ("🍺", "beer mug", "beer"),
    ("🍻", "clinking beer mugs", "beer cheers"),
    ("🍷", "wine glass", "wine"),
    ("🍸", "cocktail glass", "cocktail martini"),
    ("🥂", "clinking glasses", "cheers toast"),
    ("🍾", "bottle with popping cork", "champagne celebrate"),
    // Activities & objects
    ("⚽", "soccer ball", "soccer football"),
    ("🏀", "basketball", "basketball"),
    ("🏈", "american football", "football"),
    ("⚾", "baseball", "baseball"),
    ("🎾", "tennis", "tennis"),
    ("🏐", "volleyball", "volleyball"),
    ("🎱", "pool 8 ball", "billiards pool"),
    ("🏓", "ping pong", "table tennis"),
    ("🏸", "badminton", "badminton"),
    ("🥅", "goal net", "goal"),
    ("🎮", "video game", "game gaming controller"),
    ("🎲", "game die", "dice"),
    ("🎯", "bullseye", "target dart"),
    ("🎳", "bowling", "bowling"),
    ("🎨", "artist palette", "art paint"),
    ("🎭", "performing arts", "theater drama"),
    ("🎤", "microphone", "mic sing"),
    ("🎧", "headphone", "music headphones"),
    ("🎼", "musical score", "music"),
    ("🎵", "musical note", "music note"),
    ("🎶", "musical notes", "music notes"),
    ("🎸", "guitar", "guitar music"),
    ("🎹", "musical keyboard", "piano"),
    ("🎺", "trumpet", "trumpet"),
    ("🥁", "drum", "drum"),
    ("🏆", "trophy", "trophy win champion"),
    ("🥇", "1st place medal", "gold medal first"),
    ("🥈", "2nd place medal", "silver medal second"),
    ("🥉", "3rd place medal", "bronze medal third"),
    ("🎖️", "military medal", "medal"),
    ("🏅", "sports medal", "medal"),
    ("🎁", "wrapped gift", "gift present"),
    ("🎈", "balloon", "balloon party"),
    ("🎉", "party popper", "party celebrate tada"),
    ("🎊", "confetti ball", "confetti party"),
    ("🎃", "jack-o-lantern", "pumpkin halloween"),
    ("🎄", "christmas tree", "christmas tree"),
    ("📱", "mobile phone", "phone iphone"),
    ("💻", "laptop", "laptop computer"),
    ("🖥️", "desktop computer", "computer desktop"),
    ("⌨️", "keyboard", "keyboard"),
    ("🖱️", "computer mouse", "mouse"),
    ("🖨️", "printer", "printer"),
    ("💾", "floppy disk", "save disk"),
    ("💿", "optical disk", "cd disk"),
    ("📷", "camera", "camera photo"),
    ("📸", "camera with flash", "camera photo"),
    ("🎥", "movie camera", "film movie"),
    ("📺", "television", "tv"),
    ("🔋", "battery", "battery"),
    ("🔌", "electric plug", "plug power"),
    ("💡", "light bulb", "idea bulb light"),
    ("🔦", "flashlight", "flashlight torch"),
    ("📞", "telephone receiver", "phone call"),
    ("📟", "pager", "pager"),
    ("📠", "fax machine", "fax"),
    ("📚", "books", "books study"),
    ("📖", "open book", "book read"),
    ("📝", "memo", "note write memo"),
    ("✏️", "pencil", "pencil write"),
    ("🖊️", "pen", "pen write"),
    ("📌", "pushpin", "pin"),
    ("📎", "paperclip", "clip attach"),
    ("✂️", "scissors", "scissors cut"),
    ("📅", "calendar", "calendar date"),
    ("📆", "tear-off calendar", "calendar"),
    ("⏰", "alarm clock", "alarm clock time"),
    ("⏳", "hourglass not done", "time wait hourglass"),
    ("💰", "money bag", "money cash"),
    ("💵", "dollar banknote", "money dollar cash"),
    ("💳", "credit card", "card payment"),
    ("💎", "gem stone", "diamond gem"),
    ("🔑", "key", "key"),
    ("🔒", "locked", "lock secure"),
    ("🔓", "unlocked", "unlock"),
    ("🔔", "bell", "bell notification"),
    ("📢", "loudspeaker", "announce loud"),
    ("🔍", "magnifying glass tilted left", "search find zoom"),
    ("🔎", "magnifying glass tilted right", "search find"),
    ("🛒", "shopping cart", "cart shopping"),
    ("✉️", "envelope", "mail email"),
    ("📧", "e-mail", "email mail"),
    ("📦", "package", "box package"),
    ("🧪", "test tube", "science lab"),
    ("🔬", "microscope", "science microscope"),
    ("🔭", "telescope", "telescope astronomy"),
    ("🧹", "broom", "clean sweep"),
    ("🛏️", "bed", "bed sleep"),
    ("🚪", "door", "door"),
    ("🧯", "fire extinguisher", "extinguisher"),
    ("🧲", "magnet", "magnet"),
    ("🔨", "hammer", "hammer tool"),
    ("🪛", "screwdriver", "screwdriver tool"),
    ("🔧", "wrench", "wrench tool fix"),
    ("⚙️", "gear", "gear settings"),
    ("🧰", "toolbox", "tools"),
    ("💊", "pill", "medicine pill"),
    ("💉", "syringe", "shot vaccine"),
    // Travel & places
    ("🚗", "automobile", "car"),
    ("🚕", "taxi", "taxi cab"),
    ("🚌", "bus", "bus"),
    ("🚓", "police car", "police car"),
    ("🚑", "ambulance", "ambulance"),
    ("🚒", "fire engine", "firetruck"),
    ("🚲", "bicycle", "bike bicycle"),
    ("🛵", "motor scooter", "scooter"),
    ("🏍️", "motorcycle", "motorcycle"),
    ("✈️", "airplane", "plane flight travel"),
    ("🚀", "rocket", "rocket launch space"),
    ("🛸", "flying saucer", "ufo"),
    ("🚁", "helicopter", "helicopter"),
    ("⛵", "sailboat", "sailboat boat"),
    ("🚤", "speedboat", "boat"),
    ("🚢", "ship", "ship cruise"),
    ("🚂", "locomotive", "train"),
    ("🚆", "train", "train"),
    ("🏠", "house", "house home"),
    ("🏡", "house with garden", "home house"),
    ("🏢", "office building", "office building"),
    ("🏥", "hospital", "hospital"),
    ("🏦", "bank", "bank"),
    ("🏨", "hotel", "hotel"),
    ("🏫", "school", "school"),
    ("⛪", "church", "church"),
    ("🗽", "Statue of Liberty", "liberty newyork"),
    ("🗼", "Tokyo tower", "tokyo tower"),
    ("🌃", "night with stars", "night city"),
    ("🌉", "bridge at night", "bridge"),
    ("🎢", "roller coaster", "rollercoaster"),
    ("🎡", "ferris wheel", "ferris wheel"),
    ("⛲", "fountain", "fountain"),
    // Symbols
    ("✅", "check mark button", "check yes done correct"),
    ("✔️", "check mark", "check tick yes"),
    ("❌", "cross mark", "x no wrong cancel"),
    ("❎", "cross mark button", "x no"),
    ("➕", "plus", "plus add"),
    ("➖", "minus", "minus subtract"),
    ("➗", "divide", "divide division"),
    ("✖️", "multiply", "multiply times"),
    ("❓", "question mark", "question help"),
    ("❗", "exclamation mark", "exclamation important"),
    ("⚠️", "warning", "warning caution"),
    ("🚫", "prohibited", "no ban forbidden"),
    ("♻️", "recycling symbol", "recycle"),
    ("🔆", "bright button", "brightness bright"),
    ("🔅", "dim button", "brightness dim"),
    ("〽️", "part alternation mark", "mark"),
    ("⭕", "hollow red circle", "circle o"),
    ("🔴", "red circle", "red circle dot"),
    ("🟠", "orange circle", "orange circle"),
    ("🟡", "yellow circle", "yellow circle"),
    ("🟢", "green circle", "green circle"),
    ("🔵", "blue circle", "blue circle"),
    ("🟣", "purple circle", "purple circle"),
    ("⚫", "black circle", "black circle"),
    ("⚪", "white circle", "white circle"),
    ("🔺", "red triangle pointed up", "triangle up"),
    ("🔻", "red triangle pointed down", "triangle down"),
    ("💠", "diamond with a dot", "diamond"),
    ("🔘", "radio button", "radio button"),
    ("🔚", "end arrow", "end"),
    ("🔙", "back arrow", "back"),
    ("🔛", "on arrow", "on"),
    ("🔝", "top arrow", "top up"),
    ("🔜", "soon arrow", "soon"),
    ("➡️", "right arrow", "arrow right"),
    ("⬅️", "left arrow", "arrow left"),
    ("⬆️", "up arrow", "arrow up"),
    ("⬇️", "down arrow", "arrow down"),
    ("↗️", "up-right arrow", "arrow"),
    ("↘️", "down-right arrow", "arrow"),
    ("🔄", "counterclockwise arrows", "refresh reload sync"),
    ("🔁", "repeat", "repeat loop"),
    ("🔀", "shuffle", "shuffle random"),
    ("▶️", "play button", "play"),
    ("⏸️", "pause button", "pause"),
    ("⏹️", "stop button", "stop"),
    ("⏩", "fast-forward", "forward skip"),
    ("⏪", "fast reverse", "rewind back"),
    ("🔼", "upwards button", "up"),
    ("🔽", "downwards button", "down"),
    ("➰", "curly loop", "loop"),
    ("〰️", "wavy dash", "wave dash"),
    ("©️", "copyright", "copyright"),
    ("®️", "registered", "registered trademark"),
    ("™️", "trade mark", "trademark tm"),
    ("💲", "heavy dollar sign", "dollar money"),
    ("💱", "currency exchange", "exchange currency"),
    ("♥️", "heart suit", "heart card"),
    ("♦️", "diamond suit", "diamond card"),
    ("♠️", "spade suit", "spade card"),
    ("♣️", "club suit", "club card"),
    ("🆗", "OK button", "ok"),
    ("🆕", "NEW button", "new"),
    ("🆒", "COOL button", "cool"),
    ("🆓", "FREE button", "free"),
    ("🔞", "no one under eighteen", "18 adult"),
    ("💬", "speech balloon", "speech chat comment"),
    ("💭", "thought balloon", "thought think"),
    ("🗯️", "right anger bubble", "anger speech"),
    ("♾️", "infinity", "infinity forever"),
    ("🕐", "one o'clock", "clock time"),
    // Plain Unicode symbols (math / arrows / punctuation)
    ("→", "rightwards arrow", "arrow right"),
    ("←", "leftwards arrow", "arrow left"),
    ("↑", "upwards arrow", "arrow up"),
    ("↓", "downwards arrow", "arrow down"),
    ("↔", "left right arrow", "arrow"),
    ("⇒", "rightwards double arrow", "arrow implies"),
    ("⇔", "left right double arrow", "arrow iff"),
    ("↦", "rightwards arrow from bar", "maps to"),
    ("•", "bullet", "bullet dot point"),
    ("·", "middle dot", "dot"),
    ("…", "horizontal ellipsis", "ellipsis dots"),
    ("—", "em dash", "dash"),
    ("–", "en dash", "dash"),
    ("°", "degree sign", "degree"),
    ("±", "plus-minus sign", "plus minus"),
    ("×", "multiplication sign", "times multiply"),
    ("÷", "division sign", "divide"),
    ("≈", "almost equal to", "approx"),
    ("≠", "not equal to", "not equal"),
    ("≤", "less-than or equal to", "less equal"),
    ("≥", "greater-than or equal to", "greater equal"),
    ("∞", "infinity", "infinity"),
    ("√", "square root", "sqrt root"),
    ("π", "pi", "pi"),
    ("µ", "micro sign", "micro mu"),
    ("∑", "n-ary summation", "sum sigma"),
    ("∆", "increment", "delta change"),
    ("✓", "check mark plain", "check tick"),
    ("✗", "ballot x", "x cross"),
    ("★", "black star", "star filled"),
    ("☆", "white star", "star outline"),
    ("♥", "black heart suit", "heart"),
    ("€", "euro sign", "euro currency"),
    ("£", "pound sign", "pound gbp currency"),
    ("¥", "yen sign", "yen currency"),
    ("¢", "cent sign", "cent currency"),
    ("§", "section sign", "section"),
    ("¶", "pilcrow", "paragraph"),
    ("†", "dagger", "dagger"),
    ("‡", "double dagger", "dagger"),
    ("™", "trade mark plain", "trademark"),
    ("№", "numero sign", "number"),
];
